name: Build and Commit LaTeX PDF

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true   # Needed for committing

    - name: Build LaTeX PDF
      uses: xu-cheng/latex-action@v4
      with:
        root_file: english.tex

    - name: Rename PDF
      run: mv english.pdf halvor-cv-pdf.pdf

    - name: Commit PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add halvor-cv-pdf.pdf
        git commit -m "Update PDF [skip ci]" || echo "No changes to commit"
        git push
